### PR TITLE
Support for fully removing relations

### PR DESCRIPTION
**Pull request by tbaumann**
Fixes https://github.com/juju-solutions/layer-beats-base/issues/16

### CODE REVIEW

**Comment by tbaumann** [comment]
Sorry for not noticing 6f48e5c before. Since the hook runs every time, it writes the conf file every time and then restarts the service.
It should only restart the service if the file changed.

**Comment by chuckbutler** [comment]
@tbaumann This looks like it has overlap with #25. Could you rebase this commit with the work that landed so we can shimmy this fix in? (also are you interested in taking over maintainership of the elastic layers? :) )

**Comment by tbaumann** [comment]
Sorry @chuckbutler  I was super busy recently. I will have a look at this.  Will get back to you soon.

About maintaining. Better not, I don't know much at all about Elastic. I just added the features I needed.
And quite frankly, the project that was planned with filebeat, which I was involved with might not even work. I fear my priorities will shift away soon...

But I'm glad to help with anything. I don't mind at all to play around with charms if I have the time. :)

**Comment by tbaumann** [comment]
Done.  Was basically a whitespace fix.

**Comment by tbaumann** [comment]
Ack. This should solve #25

**Pull request merged**
